- name: pack
  color: "4b9ce2"
  description: "Pack submissions"
- name: "status:triage"
  color: "fef2c0"
  description: "Needs triage"
- name: "status:pr-open"
  color: "c2e0c6"
  description: "Draft PR opened"
- name: "status:awaiting-files"
  color: "fbca04"
  description: "Awaiting file uploads"
- name: "status:needs-changes"
  color: "e99695"
  description: "Changes requested"
- name: "status:ready-to-merge"
  color: "0e8a16"
  description: "Ready to merge"
