name: Pack submission
description: Submit a new Tenney scale pack
title: "Pack submission: <slug>"
labels: ["pack", "status:triage"]
body:
  - type: input
    id: title
    attributes:
      label: Pack title
      placeholder: "Your pack title"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Preferred slug
      description: "Use kebab-case: lowercase letters, digits, hyphens only, 3–48 chars. No spaces or underscores. Example: barthopoulos-ji-basics"
      placeholder: "example-12tet"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author display name
      placeholder: "Jane Doe"
    validations:
      required: true

  - type: input
    id: author_url
    attributes:
      label: Author URL (optional)
      placeholder: "https://example.com"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Short description
      description: "1–3 sentences."
      placeholder: "A short description of the tuning and its use."
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags (comma-separated)
      placeholder: "ji, microtonal, tutorial"
    validations:
      required: true

  - type: input
    id: root_hz
    attributes:
      label: defaults.rootHz
      description: "Numeric root frequency in Hz (e.g. 440)."
      placeholder: "440"
    validations:
      required: true

  - type: dropdown
    id: prime_limit
    attributes:
      label: defaults.primeLimit
      description: "Prime limit for the pack."
      options:
        - "5"
        - "7"
        - "11"
        - "13"
        - "17"
        - "19"
        - "23"
        - "31"
      default: 3
    validations:
      required: true

  - type: checkboxes
    id: multiple_scales
    attributes:
      label: Multiple scales per pack
      options:
        - label: "Yes, this pack includes multiple scales"
          required: false

  - type: textarea
    id: scale_files
    attributes:
      label: Scale files list
      description: |
        List the scale files you will upload.

        * One scale per line
        * Accepted formats: .scl, .ascl, .scala
        * Optional KBM per scale:
          * `myscale.scl, mymap.kbm` (comma) OR `myscale.scl | mymap.kbm` (pipe)
        * If you also fill in the single KBM filename below, it will be used for any lines that omit a KBM
      placeholder: |
        myscale.scl
        mysecond.scala, mymap.kbm
    validations:
      required: true

  - type: input
    id: kbm_file
    attributes:
      label: Optional KBM filename
      description: "Default .kbm mapping to apply to any lines above that omit a KBM."
      placeholder: "mymap.kbm"
    validations:
      required: false

  - type: checkboxes
    id: license
    attributes:
      label: License confirmation
      options:
        - label: "I confirm this pack is licensed under CC0-1.0"
          required: true

  - type: markdown
    attributes:
      value: |
        **What happens next**

        * When you submit this issue, a draft PR will be created automatically.
        * You’ll get an **“Add files now”** link that takes you straight to `packs/<slug>/sources/` on the PR branch.

        Public link to this form:
        https://github.com/stagedevices/tenney-scales/issues/new?template=pack_submission.yml
